;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        indent-for-tab-command
        mac-mwheel-scroll
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        dabbrev-expand
        end-of-buffer
        goto-line
        helm-ls-git-ls
        kill-region
        mouse-minor-mode-menu
        sgml-slash
        suspend-frame
        switch-to-buffer
        tags-loop-continue
        ))
